name: Docker Scout

on:

  workflow_dispatch:
    inputs:
      docker_image:
        required: true
        default: 'vencerems/hw0-test'
  

jobs:
  dscout:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull the image
        run: docker pull ${{ github.event.inputs.docker_image }}

      - name: Docker Scout
        uses: docker/scout-action@v1
        with:
          command: cves,recommendations,compare,sbom
          image: ${{ github.event.inputs.docker_image }}
          exit-code: false
          sarif-file: sca_scout.sarif
          output: sbom_scout.spdx.json
          format: spdx

      - name: Upload SBOM file as an artifact
        uses: actions/upload-artifact@v4
        with: 
          name: sbom_scout.spdx.json
          path: sbom_scout.spdx.json

      - name: Upload SARIF file as an artifact
        uses: actions/upload-artifact@v4
        with: 
          name: sca_scout.sarif
          path: sca_scout.sarif

      - name: Filter SARIF file
        uses: advanced-security/filter-sarif@v1
        with:
          patterns: |
            -**/*.js
          input: sca_scout.sarif
          output: sca_scout.sarif
          
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: sca_scout.sarif
          category: Security/sca_scout

      - name: SBOM upload
        uses: advanced-security/spdx-dependency-submission-action@v0.1.1
